### ISSUE TITLE
Todo: OnlineCasing

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/plugins#161]
- [x] Allow add/remove ignore words (ContextMenu)
- [ ] ~Cache names once loaded from web~
- [x] Select all matched names in ListView when user select a name from left listbox
- [x] Allow TV-show search
- [x] Add feature to export/merge names with **SubtitleEdit** default name file
- [x] Update [Plugin file](https://github.com/SubtitleEdit/plugins/blob/master/Plugins4.xml)
- [x] Clean up Packages folder
- [x] New release
